-- MySQL Script generated by MySQL Workbench
-- Sun Mar  8 22:55:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema appfluxo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `appfluxo` ;

-- -----------------------------------------------------
-- Schema appfluxo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `appfluxo` DEFAULT CHARACTER SET utf8 ;
USE `appfluxo` ;

-- -----------------------------------------------------
-- Table `appfluxo`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appfluxo`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `appfluxo`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appfluxo`.`Solicitacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appfluxo`.`Solicitacao` ;

CREATE TABLE IF NOT EXISTS `appfluxo`.`Solicitacao` (
  `idSolicitacao` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NULL,
  `observacao` VARCHAR(100) NULL,
  `pessoa_id` INT NOT NULL,
  INDEX `fk_Solicitacao_Pessoa_idx` (`pessoa_id` ASC) VISIBLE,
  PRIMARY KEY (`idSolicitacao`),
  CONSTRAINT `fk_Solicitacao_Pessoa`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `appfluxo`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `appfluxo`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `appfluxo`.`Produto` ;

CREATE TABLE IF NOT EXISTS `appfluxo`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NULL,
  `preco` DOUBLE(10,2) NULL,
  `Solicitacao_id` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Solicitacao1_idx` (`Solicitacao_id` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Solicitacao1`
    FOREIGN KEY (`Solicitacao_id`)
    REFERENCES `appfluxo`.`Solicitacao` (`idSolicitacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
